# Generated by Django 4.2.8 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningentry",
            name="role",
            field=models.CharField(default="General", max_length=120),
        ),
        migrations.RenameField(
            model_name="miningentry",
            old_name="labor_cost",
            new_name="pay_per_role",
        ),
    ]
