# Generated by Django 4.2.8 on 2026-05-04

from django.db import migrations, models


def copy_mining_payroll_entries(apps, schema_editor):
    MiningEntry = apps.get_model("core", "MiningEntry")
    PayrollEntry = apps.get_model("core", "PayrollEntry")

    payroll_entries = []
    for entry in MiningEntry.objects.all():
        role = getattr(entry, "role", "") or "General"
        pay_per_role = getattr(entry, "pay_per_role", 0) or 0
        if role == "General" and pay_per_role == 0:
            continue
        payroll_entries.append(
            PayrollEntry(
                date=entry.date,
                role=role,
                pay_per_role=pay_per_role,
                notes=f"Moved from production entry #{entry.id}",
            )
        )

    if payroll_entries:
        PayrollEntry.objects.bulk_create(payroll_entries)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_miningentry_role_rename_labor_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("role", models.CharField(max_length=120)),
                (
                    "pay_per_role",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_mining_payroll_entries, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="miningentry",
            name="pay_per_role",
        ),
        migrations.RemoveField(
            model_name="miningentry",
            name="role",
        ),
    ]
