# Generated by Django 4.2.8 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_payrollentry_remove_mining_payroll_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("UGX", "UGX - Ugandan Shilling"),
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                    ("KES", "KES - Kenyan Shilling"),
                    ("TZS", "TZS - Tanzanian Shilling"),
                    ("RWF", "RWF - Rwandan Franc"),
                    ("CNY", "CNY - Chinese Yuan"),
                ],
                default="UGX",
                max_length=3,
            ),
        ),
    ]
