# Generated by Django 4.2.8 on 2026-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quotation_quotationline'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_email',
            field=models.EmailField(default='gmiterralinkinfo@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_phone',
            field=models.CharField(default='+256 768 049 940', max_length=40),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_website',
            field=models.CharField(default='www.gmi-terralink.com', max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_address',
            field=models.TextField(default='Hamdeen Lwanga Close, Mitala Road\nLower Residence, Plot 10/12, Muyenga, Kampala'),
        ),
    ]
