# Generated by Django 4.2.8 on 2026-05-04 11:02

from django.db import migrations


def seed_warehouse_and_stock(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    InventoryItem = apps.get_model("core", "InventoryItem")
    StockLocation = apps.get_model("core", "StockLocation")
    StockMovement = apps.get_model("core", "StockMovement")

    main_wh, _ = Location.objects.get_or_create(
        code="MAIN-WH",
        defaults={
            "name": "Main Warehouse",
            "kind": "Warehouse",
            "is_default_warehouse": True,
        },
    )
    if not main_wh.is_default_warehouse:
        main_wh.is_default_warehouse = True
        main_wh.save()

    for item in InventoryItem.objects.all():
        qty = item.stock_on_hand or 0
        StockLocation.objects.update_or_create(
            item=item,
            location=main_wh,
            defaults={"quantity": qty},
        )
        if qty > 0:
            StockMovement.objects.create(
                kind="Purchase",
                item=item,
                quantity=qty,
                destination=main_wh,
                reference="SEED",
                note="Initial stock seeded from legacy stock_on_hand",
            )


def reverse_seed(apps, schema_editor):
    StockMovement = apps.get_model("core", "StockMovement")
    StockLocation = apps.get_model("core", "StockLocation")
    Location = apps.get_model("core", "Location")
    StockMovement.objects.filter(reference="SEED").delete()
    StockLocation.objects.all().delete()
    Location.objects.filter(code="MAIN-WH").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_brand_location_stockmovement_category_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_warehouse_and_stock, reverse_seed),
    ]
