# Generated by Django 4.2.8 on 2026-05-04 11:40

from django.db import migrations


def seed_main_store(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    Location.objects.get_or_create(
        is_default_store=True,
        defaults={
            "name": "Main Store",
            "code": "MAIN-STORE",
            "kind": "Store",
        },
    )


def reverse_seed(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    Location.objects.filter(is_default_store=True, code="MAIN-STORE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_inventoryitem_selling_price_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_main_store, reverse_seed),
    ]
