# Generated by Django 4.2.8 on 2026-05-07 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_seed_main_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='date_stocked',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Reserved', 'Reserved')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse_position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight_or_volume',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sale_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('General Manager', 'General Manager'), ('Finance', 'Finance'), ('Warehouse', 'Warehouse'), ('Warehouse Manager', 'Warehouse Manager'), ('Sales', 'Sales'), ('Sales Attendant', 'Sales Attendant'), ('Store Manager', 'Store Manager'), ('Operations', 'Operations')], default='Sales', max_length=20),
        ),
    ]
