# Generated by Django 5.0.6 on 2026-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inventoryitem_barcode_inventoryitem_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='department',
            field=models.CharField(choices=[('Mining', 'Mining'), ('Payroll', 'Payroll')], default='Mining', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='mining_activity',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='worker_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
