# Generated by Django 5.0.6 on 2026-05-15 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payrollentry_department_payrollentry_mining_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('General Manager', 'General Manager'), ('Procurement', 'Procurement'), ('Finance', 'Finance'), ('Warehouse', 'Warehouse'), ('Warehouse Manager', 'Warehouse Manager'), ('Sales', 'Sales'), ('Sales Attendant', 'Sales Attendant'), ('Store Manager', 'Store Manager'), ('Operations', 'Operations')], default='Sales', max_length=20),
        ),
        migrations.CreateModel(
            name='NoticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('General Manager', 'General Manager'), ('Procurement', 'Procurement'), ('Finance', 'Finance'), ('Warehouse', 'Warehouse'), ('Warehouse Manager', 'Warehouse Manager'), ('Sales', 'Sales'), ('Sales Attendant', 'Sales Attendant'), ('Store Manager', 'Store Manager'), ('Operations', 'Operations')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed_at', '-created_at'],
            },
        ),
    ]
