# Generated by Django 5.0.6 on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_userprofile_role_noticetask"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="parent_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="split_orders",
                to="core.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="split_from_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="split_orders",
                to="core.purchaseorderline",
            ),
        ),
    ]
